### ISSUE TITLE
Question about the 0.5 deformation field

### ISSUE THREAD

**Issue by iCherishxixixi** [cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks#13]
Hi, 
    Thanks for sharing your code.  After reading your paper, I have some question about the 0.5 deformation field. 
    The paper says the 0.5 deformation field is obtained by the recurrence φ^(1/2^(t−1) )=φ^(1/2^t ) o φ^(1/2^t ) until t=2. However,  the 0.5 deformation field is calculated by class DiffeomorphicTransform in the code and  the recurrence is terminated until t=1. Would it be better if **for _ in range(self.time_step)** is changed to **for _ in range(self.time_step-1)** in class DiffeomorphicTransform or there is something wrong with my understanding.
![1](https://user-images.githubusercontent.com/58366819/183451663-efd90ae2-0d4f-4ee0-bcf7-603a154e946a.PNG)

**Comment by cwmok** [comment]
@iCherishxixixi 
Yes, you are correct. We have put a special [note](https://github.com/cwmok/Fast-Symmetric-Diffeomorphic-Image-Registration-with-Convolutional-Neural-Networks/blob/master/README.md#notes-on-this-repository) in the readme file regarding this issue. Both approaches can achieve diffeomorphic solutions. 

"We found that estimating the time 1 solution instead of 0.5 solution tends to produce a smoother result in our later experiments. If you want to switch back to 0.5 solution, please replace the "self.time_step" with "self.time_step-1" at line 165 in Models.py and train a new model from scratch."

**Comment by iCherishxixixi** [comment]
Thank you very much!
